name: Build launcher

on:
  workflow_dispatch:
  push:
    branches: '*'

jobs:
  build:
    strategy:
      matrix:
        config:
        - name: Release
          lower: release

        - name: Debug
          lower: debug

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup Java JDK
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        java-version: 21
        distribution: temurin
        cache: gradle

    - name: Fix gradle permissions
      run: chmod +x ./gradlew

    - name: Build project
      run: |
        ./gradlew app:assemble${{ matrix.config.name }} 

    - name: Upload release build
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      if: ${{ matrix.config.lower == 'release' }}
      with:
        name: geode-launcher-${{ matrix.config.lower }}
        path: |
          ${{github.workspace}}/app/build/outputs/apk/${{ matrix.config.lower }}/app-universal-${{ matrix.config.lower }}-unsigned.apk

          ${{ steps.rename_apk.outputs.path }}
          ${{ steps.rename_mappings.outputs.path }}

    - name: Upload debug build
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      if: ${{ matrix.config.lower == 'debug' }}
      with:
        name: geode-launcher-${{ matrix.config.lower }}
        path: |
          ${{ steps.rename_apk_universal.outputs.path }}
          ${{ steps.rename_apk.outputs.path }}